######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 10 13:56:07 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += qt

# Input
HEADERS += SolGUI.h CardDeck.h CardColumn.h Board.h
SOURCES += main.cpp SolGUI.cpp CardDeck.cpp CardColumn.cpp Board.cpp
